major=1
version=$(major).2.0

CFLAGS?=-g -O2 -fPIC -fvisibility=hidden
LDLIBS?=-lm
PREFIX?=/usr/local

CDEPFLAGS=-MD -MP -MT $@ -MF $*.dep
SHAREDFLAGS=-shared -Wl,-soname,libsgode.so.$(major)
DIFF=git --no-pager diff --exit-code --no-index
harness=$(HARNESS) timeout 15

-include config.mk

CPPFLAGS+=-DSG_BUILD -I.

all: lib/libsgode.so

clean:
	rm -fr bin lib target *.dep *.o */*.dep */*.o */*.out

install: all
	install -d $(DESTDIR)$(PREFIX)/include/sg_ode $(DESTDIR)$(PREFIX)/lib
	install -m644 -t $(DESTDIR)$(PREFIX)/include sg_ode.h
	install -m644 -t $(DESTDIR)$(PREFIX)/include/sg_ode sg_ode/extern.h sg_ode/ode.h sg_ode/restrict_begin.h sg_ode/restrict_end.h sg_ode/vector.h
	install -m755 -t $(DESTDIR)$(PREFIX)/lib lib/libsgode.so.$(version)
	cp -P lib/libsgode.so lib/libsgode.so.$(major) $(DESTDIR)$(PREFIX)/lib

lib/libsgode.so: lib/libsgode.so.$(major)
	ln -fs libsgode.so.$(major) $@

lib/libsgode.so.$(major): lib/libsgode.so.$(version)
	ln -fs libsgode.so.$(version) $@

lib/libsgode.so.$(version): sg_ode/ode.o sg_ode/vector.o
	@mkdir -p $(@D)
	$(CC) $(LDFLAGS) $(SHAREDFLAGS) -o $@ $^ $(LDLIBS)

check: bin/jacobian_elliptic_a_test.ok bin/jacobian_elliptic_b_test.ok

bin/%_test.ok: bin/%_test tests/%$(TESTSUFFIX).txt
	@mkdir -p $(@D)
	$(harness) $(@:.ok=) $(TESTFLAGS) >$(@:.ok=.out)
	$(DIFF) $(@:.ok=.out) $(word 2,$^)
	@touch $@

bin/jacobian_elliptic_a_test: tests/main.o sg_ode/ode.o sg_ode/vector.o tests/jacobian_elliptic_a.o
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS)

bin/jacobian_elliptic_b_test: tests/main.o sg_ode/ode.o sg_ode/vector.o tests/jacobian_elliptic_b.o
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS)

sg_ode/vector_macros.h: sg_ode/vector_macros.py
	@mkdir -p $(@D)
	./$<

doc:
	doxygen

deploy-doc: doc/html/.git/config doc
	cd $(<D)/.. && \
	git add -A && \
	git commit --amend -q -m Autogenerated && \
	git push -f origin master:gh-pages

doc/html/.git/config:
	mkdir -p $(@D)
	url=`git remote -v | grep origin | awk '{ printf "%s", $$2; exit }'` && \
	cd $(@D)/.. && \
	git init && \
	git config user.name Bot && \
	git config user.email "<>" && \
	git commit -m _ --allow-empty && \
	git remote add origin "$$url"

# ------------------------------------------------------------------------
# Lint rules
#
# Notes
#
#   - All sanitizers are run in subdirectories of 'target' to avoid polluting
#     the main tree.
#   - If the sanitizer fails to mmap, it's probably due to ulimit.
#   - Address and memory sanitizers require all external libraries to be
#     recompiled, so we're avoid sanitizing any tests that require MPI.

target/clang_asan: makeflags=CC=clang CFLAGS='$(CFLAGS) -fsanitize=address' check
target/clang_msan: makeflags=CC=clang CFLAGS='$(CFLAGS) -fsanitize=memory' check
target/clang_ubsan: makeflags=CC=clang CFLAGS='$(CFLAGS) -fsanitize=undefined' check
target/dump_state: makeflags=TESTFLAGS=--dump-state TESTSUFFIX=_state check
target/gcc_valgrind: makeflags=CC=gcc CFLAGS='$(CFLAGS) -O3' HARNESS='valgrind --error-exitcode=1 -q' check

lints!=sed -n 's|^\(target/[^:%][^:%]*\).*|\1|p' Makefile

lint: $(lints)
	echo $^

# We must add a list of all patterns for source files for vpath builds
# If make complains about missing files when linting this is probably why
$(lints):
	@mkdir -p $@
	@printf '' >$@/Makefile
	@echo vpath %.c ../../ >>$@/Makefile
	@echo vpath %.h ../../ >>$@/Makefile
	@echo vpath %.inl ../../ >>$@/Makefile
	@echo vpath %.py ../../ >>$@/Makefile
	@echo vpath %.txt ../../ >>$@/Makefile
	@echo include ../../Makefile >>$@/Makefile
	+$(MAKE) -C $@ $(makeflags)

# ------------------------------------------------------------------------
# Generic rules

.c.o:
	@mkdir -p $(@D)
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CDEPFLAGS) -c -o $@ $<

.SUFFIXES: .c .o

.PHONY: Makefile all check deploy-doc doc install lint $(lints)

-include $(wildcard *.dep) $(wildcard */*.dep)
